dist: trusty

os:
  - linux

language: go

go: 1.7
go_import_path: github.com/zalando-incubator/mate

script: IMAGE=499577160181.dkr.ecr.eu-west-1.amazonaws.com/teapot/mate make build.docker

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region eu-west-1)
  - IMAGE=499577160181.dkr.ecr.eu-west-1.amazonaws.com/teapot/mate make build.push
